targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
          scalars:
            DateTime:
              type: String
            Decimal:
              type: String
            JSON:
              type: dynamic
